[phases.setup]
nixPkgs = ["...", "nodejs_20"]

[phases.build]
cmd = "cd apps/backend && npm install && npm run build"

[start]
cmd = "cd apps/backend && npm start"

[variables]
NODE_ENV = "production"
PORT = "4000"
